# Generated by Django 5.1.4 on 2025-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlightcentral', '0006_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
