# Generated by Django 5.1.4 on 2025-01-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlightcentral', '0007_post_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
